nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 10.0.0.6
    - name: node-2
      ip: 10.0.0.7
    # - name: node-3
    #   ip: <indexer-node-ip>

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazuh-1
      ip: 10.0.0.10
    node_type: master
    - name: wazuh-2
      ip: 10.0.0.11
    node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 10.0.0.20